version: '3.8'

services:
  mailing-db:
    image: postgres:16
    container_name: mailing-postgres-db
    restart: always
    environment:
      POSTGRES_USER: mailing_user
      POSTGRES_PASSWORD: mailing_password
      POSTGRES_DB: mailingdb
    ports:
      - "3333:5432"
    volumes:
      - mailing_db_data:/var/lib/postgresql/data

volumes:
  mailing_db_data: